ALTER TABLE "Habit" ADD COLUMN IF NOT EXISTS "targetValue" INTEGER;
ALTER TABLE "Habit" ADD COLUMN IF NOT EXISTS "targetUnit" TEXT;
ALTER TABLE "HabitLog" ADD COLUMN IF NOT EXISTS "valueDone" INTEGER;
